tagsParam:
  name: tags
  in: query
  description: tags to filter by
  required: false
  type: array
  collectionFormat: csv
  items:
    type: string
limitsParam:
  name: limit
  in: query
  description: maximum number of results to return
  required: false
  type: integer
  format: int32
prueba:
  name: pet
  in: body
  description: Pet to add to the store
  required: true
  schema:
    type: array
    items:
      type: string


