tagsParam:
  name: tags
  in: query
  description: tags to filter by
  required: false
  type: array
  collectionFormat: csv
  items:
    type: string
limitsParam:
  name: limit
  in: query
  description: maximum number of results to return
  required: false
  type: integer
  format: int32
pet:
  type: object
    required:
    - id
    - name
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
    tag:
      type: string
